### ISSUE TITLE
Hand Unit Testing

### ISSUE THREAD

**Issue by AidanD-boot** [MunkyCode/CardGameDemo#45]
Learn unit testing with Jest and Enzyme. Apply to hands for user and dealer

How-to demo:
-Unit tests for the user's hand count
-Unit tests for the dealer's hand count
-Unit tests for the hiding of Dealer's second card

**Comment by AidanD-boot** [comment]
Included time to learn about testing with Enzyme

**Comment by tobydragon** [comment]
3 hours total. Hand now has unit tests with enzyme
