### ISSUE TITLE
Card sizing/placement

### ISSUE THREAD

**Issue by AidanD-boot** [MunkyCode/CardGameDemo#77]
Cards will be sized the same and layed out with space between them.

How-to demo:
Cards will display as a set height and width. With a small amount of space between each card.

**Comment by AidanD-boot** [comment]
Can't get styling rules to apply to the card components

**Comment by tobydragon** [comment]
Can you get these styling rules to apply in other contexts, like in an example in codesandbox? Can you make any changes to the styling rules and see their effects? For example, as far as I know, the text on cards would be left justified, but in BlackJack.css it has .card set to text-align: center. If you change that do you see a change?

**Comment by AidanD-boot** [comment]
Used the first flex-box tutorial in the front-end resource document. Found a styling rule called "max-width" which keeps the cards from expanding past a specific width.
