### ISSUE TITLE
Snapshot testing

### ISSUE THREAD

**Issue by AidanD-boot** [MunkyCode/CardGameDemo#86]
I will learn about react's snapshot testing abilities. I will show my progress by making a snapshot test for when a card is added to the user's hand.

How-to demo:
The snapshot test will check the initial game state, then check again after the user adds a card to their hand. The test should appear to "fail" since the two game states will be different.

**Comment by tobydragon** [comment]
2 hours

demoed by: 

- making a snapshot, then seeing the test pass 
- changing the content of the page, seeing the test fail
- updating the snapshot seeing the test pass
- reverting the change to the content, seeing the test fail again
- updating the snapshot again to return it to its original state, seeing the test pass again
